### ISSUE TITLE
Demo links on your Readme don't point to a demo, but instead a seemingly malicious site

### ISSUE THREAD

**Issue by joeskeen** [fritx/img2txt#1]
You really need to look at the links in your readme.  I think they go to a malicious website.
You can probably host whatever demos you need to on GitHub pages, which is free and included with this repository.  Just create a `gh-pages` branch with the demo page content and it will automatically host it so you can link to it in your README.

**Comment by fritx** [comment]
Thanks for reminding!
It was part of the original source of https://github.com/hit9/img2txt
